### ISSUE TITLE
Isn't defined

### ISSUE THREAD

**Issue by EricBridoux** [pbissonho/Flutter-Authentication#1]
Hi, I'm very new in Flutter,
I'm testing your example but have 2 issues

1: removeToken -> isn't defined
Future<void> unauthenticate() async {
    await fresh.removeToken();
  }

2 : _client.fresh.currentToken -> isn't defined too
in :
 Stream<IdentiyUser> get currentUser async* {
    yield* _client.fresh.currentToken.map((token) {
      if (token == null) return IdentiyUser(email: '', userName: '', roles: [], accessClaims: []);
      return IdentiyUser.fromToken(token);
    });
  }

thx

**Comment by pbissonho** [comment]
Hello @EricBridoux 
I was using a fresh_dio fork in this project, I ended up making some modifications to my fork to open a pull request to the fresh_dio official repository, but after these changes, this project has not yet been updated.

I will update the project to use the most current version of [fresh_dio](https://github.com/felangel/fresh).

Thank you for reminding me that this project has not yet been updated.

**Comment by pbissonho** [comment]
Fixed issues and updated dependencies
https://github.com/pbissonho/Aukin/pull/2.

I haven't tested everything, but I believe it's working. If you encounter any problems, feel free to open another issue.

I really appreciate any kind of contribution, reporting errors or suggestions for improvements.
